[files]
# Include Markdown recursively, including documentation in hidden directories.
ignore-hidden = false
extend-exclude = ["*", "!*/", "!*.md", ".git", "node_modules", "vendor"]

[default]
locale = "en-us"

[default.extend-words]
aks = "aks" # Azure Kubernetes Service
CAF = "CAF" # Azure Cloud Adoption Framework
yor = "yor" # Infrastructure tagging tool

[default.extend-identifiers]
SyncVey = "SyncVey" # AWS asset ledger project
