name: misspell

on:
  push:
    branches:
      - master
    paths:
      - '**.md'
      - '.typos.toml'
      - '.github/workflows/misspell.yml'
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

permissions:
  contents: read

jobs:
  misspell:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Check Markdown spelling
        uses: crate-ci/typos@512fc24f32f44ab01972217aaaf3dc86ec234d53 # v1.50.2
        with:
          config: .typos.toml
