name: misspell

on:
  push:
    branches:
      - master
    paths:
      - '**.md'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.md'

permissions:
  contents: read

jobs:
  misspell:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: misspell
        uses: reviewdog/action-misspell@d6429416b12b09b4e2768307d53bef58d172e962 # v1
        with:
          locale: "US"
