name: notfoundbot

on:
  push:
    branches:
      - master
  schedule:
    - cron: "12 4 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Fix links
        uses: tmcw/notfoundbot@feeb668347f9c0ef8abdc4a8c43778fce2ee85d9 # v3.1.0
        continue-on-error: true
        with:
          content-folder: '.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXCEPTIONS: github.com developer.hashicorp.com www.hashicorp.com medium.com blog.pelo.tech terraformbook.com
